server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false


  datasource:
    url: "jdbc:postgresql://ec2-34-233-43-35.compute-1.amazonaws.com:5432/dchs8hjllv2hpg"
    username: oootxhjxsxqdfe
    password: c7363409310a495704137d4816f51b25c6734563c00649c844e6476caa41f288

    hikari:
      minimum-idle: 2
      maximum-pool-size:  10
      idle-timeout:  30000
      max-lifetime:  60000
      connection-timeout:  20000
      auto-commit:  true